"""Configuration loading.

Secrets (Blink login, your phone number) live in ``.env``; everything else —
camera name, polling cadence, and the parking-spot regions — lives in
``config.json`` (generated by ``calibrate.py``).
"""
from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
CONFIG_PATH = PROJECT_ROOT / "config.json"
CREDS_PATH = DATA_DIR / "blink_creds.json"

# Load .env once, on import, so the auth/calibrate scripts can read secrets
# without needing config.json to exist yet.
load_dotenv(PROJECT_ROOT / ".env")


@dataclass(frozen=True)
class Spot:
    """A parking spot as an (x, y, w, h) rectangle in image pixels."""

    id: str
    box: tuple[int, int, int, int]


@dataclass(frozen=True)
class Config:
    camera_name: str
    poll_interval_seconds: int
    confidence_threshold: float
    overlap_threshold: float
    debounce_frames: int
    vehicle_classes: frozenset[str]
    model_path: str
    snapshot_path: Path
    spots: list[Spot]
    blink_username: str
    blink_password: str
    imessage_recipient: str


def load_config(path: Path = CONFIG_PATH) -> Config:
    if not path.exists():
        raise FileNotFoundError(
            f"{path} not found. Run `python calibrate.py` first to define your "
            "parking spots."
        )
    raw = json.loads(path.read_text())

    spots = [Spot(id=s["id"], box=tuple(s["box"])) for s in raw.get("spots", [])]
    if not spots:
        raise ValueError(f"No spots defined in {path}. Re-run `python calibrate.py`.")

    return Config(
        camera_name=raw["camera_name"],
        poll_interval_seconds=int(raw.get("poll_interval_seconds", 60)),
        confidence_threshold=float(raw.get("confidence_threshold", 0.35)),
        overlap_threshold=float(raw.get("overlap_threshold", 0.15)),
        debounce_frames=int(raw.get("debounce_frames", 2)),
        vehicle_classes=frozenset(
            raw.get("vehicle_classes", ["car", "truck", "bus", "motorcycle"])
        ),
        model_path=raw.get("model_path", "yolov8n.pt"),
        snapshot_path=DATA_DIR / raw.get("snapshot_file", "latest.jpg"),
        spots=spots,
        blink_username=_require_env("BLINK_USERNAME"),
        blink_password=_require_env("BLINK_PASSWORD"),
        imessage_recipient=_require_env("IMESSAGE_RECIPIENT"),
    )


def _require_env(key: str) -> str:
    value = os.environ.get(key, "").strip()
    if not value:
        raise EnvironmentError(
            f"{key} is not set. Copy .env.example to .env and fill it in."
        )
    return value
